version: "3.9"
services:
  webapp:
    build: .
    ports:
      - "8080:8080"
  mongodb:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - "8081:27017"