version: "3.9"
services:
  webapp:
    build: .
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:8080"
  mongodb:
    image: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:27017"